name: Build extension

on:
  push:

jobs:
  build-and-zip:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "now=$(date +'%Y%m%d-%H%M')" >> "$GITHUB_ENV"
      - run: yarn
      - name: Build Production
        if: ${{ github.ref_name == 'main' }}
        run: yarn build:all --mode production
      - name: Build Staging
        if: ${{ github.ref_name != 'main' }}
        run: yarn build:all --mode staging
      - run: yarn zip:all
      - uses: actions/upload-artifact@v4
        with:
          name: preview-extension-chrome-${{ env.now }}
          path: dist/chrome.zip
      - uses: actions/upload-artifact@v4
        with:
          name: preview-extension-firefox-${{ env.now }}
          path: dist/firefox.zip
