name: Zip Files

on:
  push:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - uses: vimtor/action-zip@v1
        with:
          files: dist/manifest.json
          dest: foresight-extension.zip
      - uses: actions/upload-artifact@v3
        with:
          name: foresight-extension
          path: foresight-extension.zip
