name: Zip Files

on:
  push:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "now=$(date +'%Y%m%d-%H%M')" >> "$GITHUB_ENV"
      - run: yarn
      - run: yarn build
      - run: zip -r foresight-extension.zip ./dist/
      - uses: actions/upload-artifact@v3
        with:
          name: foresight-extension-${{ env.now }}
          path: foresight-extension.zip
