name: Zip Files

on:
  push:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H%M')"
      - run: yarn
      - run: yarn build
      - uses: vimtor/action-zip@v1.1
        with:
          files: dist
          dest: foresight-extension.zip
      - uses: actions/upload-artifact@v3
        with:
          name: foresight-extension-${ env.NOW }
          path: foresight-extension.zip
