name: Zip Files

on:
  push:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "now=$(date +'%Y%m%d-%H%M')" >> "$GITHUB_ENV"
      - run: yarn
      - name: Build Production
        if: ${{ github.ref_name == 'main' }}
        run: yarn build --production
      - name: Build Staging
        if: ${{ github.ref_name != 'main' }}
        run: yarn build --staging
      - run: zip -r foresight-extension.zip ./dist/
      - uses: actions/upload-artifact@v3
        with:
          name: foresight-extension-${{ env.now }}
          path: foresight-extension.zip
