name: Pull Request Checks
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: pr-checks-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint, Prettier & TSC
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn tsc
      - run: yarn lint
      - run: yarn prettier --check .
      # - run: yarn test:ci
      # - name: Upload coverage reports to Codecov with GitHub Action
      #   uses: codecov/codecov-action@v3
      # - name: Test Report
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()
      #   with:
      #     name: Frontend Unit Test Results
      #     path: "coverage/jest-*.xml"
      #     reporter: jest-junit
      # - name: Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     directory: ./coverage
      #     fail_ci_if_error: true
      #     verbose: true
